const data = {
  products: [
    {
      name: 'Nike Slim Shirt',
      slug: 'nile-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg',
      price: 450,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Nike Slim pant',
      slug: 'nile-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 600,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality pant',
    },
    {
      name: 'Adidas Slim Shirt',
      slug: 'adidas-slim-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 550,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Slim pant',
      slug: 'adidas-slim-pant',
      category: 'Pants',
      image: '/images/p4.jpg',
      price: 650,
      countInStock: 10,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality pant',
    },
  ],
};
export default data;
